version: '3.8'

services:
  web:
    build:
      context: ./inkwell_backend
      dockerfile: Dockerfile
    command: python manage.py collectstatic --noinput && gunicorn inkwell_backend.wsgi:application --bind 0.0.0.0:$PORT
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SETTINGS_MODULE=inkwell_backend.settings
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0

  frontend:
    build:
      context: ./inkwell-frontend
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
