# Generated by Django 5.0.6 on 2024-05-28 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_profiles',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='user_visited_profiles', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visitors',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='user_visitors', to='users.userprofile'),
        ),
    ]
