# Generated by Django 5.0.6 on 2024-07-24 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_comments_remove_book_dislikes_and_more'),
        ('users', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_books',
        ),
        migrations.AlterField(
            model_name='bookcollection',
            name='books',
            field=models.ManyToManyField(related_name='collections', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookcollection',
            unique_together={('user', 'name')},
        ),
    ]
