# Generated by Django 5.0.6 on 2024-07-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_liked_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower_count_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='geographic_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_book_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_book_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
