# Generated by Django 5.0.6 on 2024-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follower_count_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='geographic_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
