# Generated by Django 5.0.6 on 2024-05-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='book_comments', to='comments.comment'),
        ),
    ]
