# Generated by Django 5.0.6 on 2024-05-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('recommendations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_books_set', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_books_set', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='book',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='book_recommendations', to='recommendations.recommendation'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='books.genre'),
        ),
    ]
