# Generated by Django 5.0.6 on 2024-06-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_name_author_first_name_author_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
