# Generated by Django 5.0.6 on 2024-07-29 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_comments_remove_book_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='completed_reads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='geographic_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='book',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='total_reading_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='book',
            name='unique_view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
