# Generated by Django 5.0.6 on 2024-08-03 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_completed_reads_book_geographic_distribution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('upload_type', models.CharField(max_length=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='book_drafts/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='book_draft_covers/')),
                ('banner_picture', models.ImageField(blank=True, null=True, upload_to='book_draft_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
