# Generated by Django 5.0.6 on 2024-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdraft',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookdraft',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookdraft',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookdraft',
            name='upload_type',
            field=models.CharField(default='pdf', max_length=10),
        ),
    ]
