# Generated by Django 5.0.6 on 2024-08-06 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookdraft_description_alter_bookdraft_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookdraft',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='book_drafts/banners/'),
        ),
        migrations.AlterField(
            model_name='bookdraft',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='book_drafts/covers/'),
        ),
        migrations.AlterField(
            model_name='bookdraft',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book_drafts/pdfs/'),
        ),
    ]
