name: Deploy Frontend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'inkwell-frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "inkwell-frontend"
          heroku_email: "ayman.afeef@gmail.com"
          appdir: "inkwell-frontend"
          procfile: "web: npm start"