name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'inkwell_backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "inkwell-backend"
          heroku_email: "ayman.afeef@gmail.com"
          appdir: "inkwell_backend"
          procfile: "web: gunicorn inkwell_backend.wsgi --log-file -"